@urlPrefia = http://localhost:80
@generatorId = generator_10_10
@positionLat = 10
@positionLng = 10
@radiusKm = 10
@geoOrderCountLimit = 100
@ratePerSecond = 10

### Create a new generator

POST {{urlPrefia}}/generator/{{generatorId}}/create
Content-Type: application/json

{
  "generatorId": "{{generatorId}}",
  "position": {
    "lat": {{positionLat}},
    "lng": {{positionLng}}
  },
  "radiusKm": {{radiusKm}},
  "geoOrderCountLimit": {{geoOrderCountLimit}},
  "ratePerSecond": {{ratePerSecond}}
}
