@urlPrefix = http://localhost:9000
@orderSkuItemId = 3ac07364-29e4-4213-89bf-48218df0f6cb_49cdb94a-f2e4-45b2-8a64-7ced590e1405

### get order sku item

GET {{urlPrefix}}/order-sku-item/{{orderSkuItemId}}
