
# @urlPrefix = https://empty-moon-4960.us-east1.kalix.app
@urlPrefix = http://localhost:9000
@customerId = customer-1
@cartId = cart-1
@skuId = sku-2
@skuName = sku name 2
@quantity = 3

### add item

PUT {{urlPrefix}}/cart/{{cartId}}/items/add
Content-Type: application/json

{
  "cartId":"{{cartId}}",
  "customerId":"{{customerId}}",
  "skuId":"{{skuId}}",
  "skuName":"{{skuName}}",
  "quantity":{{quantity}}
}

### change item

PUT {{urlPrefix}}/cart/{{cartId}}/items/{{skuId}}/change
Content-Type: application/json

{
  "cartId":"{{cartId}}",
  "skuId":"{{skuId}}",
  "quantity":{{quantity}}
}

### remove item

PUT {{urlPrefix}}/cart/{{cartId}}/items/{{skuId}}/remove
Content-Type: application/json

{
  "cartId":"{{cartId}}",
  "skuId":"{{skuId}}"
}

### checkout

PUT {{urlPrefix}}/cart/{{cartId}}/checkout
Content-Type: application/json

{
  "cartId":"{{cartId}}"
}

### delete

DELETE {{urlPrefix}}/cart/{{cartId}}/delete
Content-Type: application/json

{
  "cartId":"{{cartId}}"
}

### get

GET {{urlPrefix}}/cart/{{cartId}}

### add item with missing fields

PUT {{urlPrefix}}/cart/{{cartId}}/items/add
Content-Type: application/json

{
  "cartId":"{{cartId}}",
  "customerId":"",
  "skuId":"",
  "skuName":"",
  "quantity":0
}
