
# @urlPrefix = https://empty-moon-4960.us-east1.kalix.app
@urlPrefix = http://localhost:9000
@customerId = customer-1
@skuId = sku-1
@skuName = sku name 1
@quantity = 3

### add item

PUT {{urlPrefix}}/cart/{{customerId}}/items/add
Content-Type: application/json

{
  "customerId":"{{customerId}}",
  "skuId":"{{skuId}}",
  "skuName":"{{skuName}}",
  "quantity":{{quantity}}
}

### change item

PUT {{urlPrefix}}/cart/{{customerId}}/items/{{skuId}}/change
Content-Type: application/json

{
  "customerId":"{{customerId}}",
  "skuId":"{{skuId}}",
  "quantity":{{quantity}}
}

### remove item

PUT {{urlPrefix}}/cart/{{customerId}}/items/{{skuId}}/remove
Content-Type: application/json

{
  "customerId":"{{customerId}}",
  "skuId":"{{skuId}}"
}

### checkout

PUT {{urlPrefix}}/cart/{{customerId}}/checkout
Content-Type: application/json

{
  "customerId":"{{customerId}}"
}

### get

GET {{urlPrefix}}/cart/{{customerId}}

### add item with missing fields

PUT {{urlPrefix}}/cart/{{customerId}}/items/add
Content-Type: application/json

{
  "customerId":"{{customerId}}",
  "skuId":"",
  "skuName":"",
  "quantity":0
}
