@urlPrefix = http://localhost:9000
@stockOrderId = stock-order-1
@skuId = sku-1
@skuName = sku-name-1
@orderItemsTotal = 10
@orderItemsOrdered = 5
@orderItemsAvailable = 5

### Create a new stock order

POST {{urlPrefix}}/stock-order/{{stockOrderId}}/create
Content-Type: application/json

{
  "stockOrderId": "{{stockOrderId}}",
  "skuId": "{{skuId}}",
  "skuName": "{{skuName}}",
  "orderItemsTotal": {{orderItemsTotal}}
}

### Create a new stock order (bad request)

PUT {{urlPrefix}}/stock-order/{{stockOrderId}}/create
Content-Type: application/json

{
  "stockOrderId": "",
  "skuId": "",
  "skuName": "",
  "orderItemsTotal": 0
}

### Update a stock order

PUT {{urlPrefix}}/stock-order/{{stockOrderId}}/update
Content-Type: application/json

{
  "stockOrderId": "{{stockOrderId}}",
  "orderItemsOrdered": {{orderItemsOrdered}},
  "orderItemsAvailable": {{orderItemsAvailable}}
}

### Generate stock sku items

PUT {{urlPrefix}}/stock-order/{{stockOrderId}}/generate-stock-sku-item-ids
Content-Type: application/json

{
  "stockOrderId": "{{stockOrderId}}"
}

### Get a stock order

GET {{urlPrefix}}/stock-order/{{stockOrderId}}
