@urlPrefix = http://localhost:9000
@stockOrderId = stock-order-1
@lotLevel = 1
@lotNumber = 1
@skuId = sku-1
@skuName = sku-name-1
@stockSkuItemNumber = 9
@entityId = stock-order-1_2_3_9

### Create a stock sku item

POST {{urlPrefix}}/stock-sku-item/{{entityId}}/create
Content-Type: application/json

{
  "stockSkuItemId": {
    "stockOrderLotId": {
      "stockOrderId": "{{stockOrderId}}",
      "lotLevel": {{lotLevel}},
      "lotNumber": {{lotNumber}}
    },
    "stockSkuItemNumber": {{stockSkuItemNumber}}
  },
  "skuId": "{{skuId}}",
  "skuName": "{{skuName}}"
}

### Get a stock sku item

GET {{urlPrefix}}/stock-sku-item/{{entityId}}
