@urlPrefix = http://localhost:9000
@geoOrderId = geoOrder-id_36.1202610336205_-115.1386047020768

# @topLeftLat = 11.0
# @topLeftLng = 9.0
# @botRightLat = 9.0
# @botRightLng = 11.0
@topLeftLat = 90.0
@topLeftLng = -180.0
@botRightLat = -90.0
@botRightLng = 180.0
@nextPageToken =

###

GET {{urlPrefix}}/geo-order/{{geoOrderId}}

###

PUT {{urlPrefix}}/geo-order/{{geoOrderId}}/ping
Content-Type: application/json

{
  "geoOrderId":"{{geoOrderId}}"
}

### TODO for testing
PUT {{urlPrefix}}/geo-order/{{geoOrderId}}/toggle-alarm

### Get geoOrders by location

GET {{urlPrefix}}/geo-orders/by-location/{{topLeftLat}}/{{topLeftLng}}/{{botRightLat}}/{{botRightLng}}?nextPageToken={{nextPageToken}}
