@urlPrefix = http://localhost:9000
# @urlPrefix = https://flat-lab-5598.eu-central-1.kalix.app
//today's date in iso format
@orderedAtFrom = 2024-01-01T00:00:00.000Z
@orderedAtTo = 2025-12-31T23:59:59.999Z
@nextPageToken = ABCD
@customerId = customer-1

### Get all orders in from/to range

POST {{urlPrefix}}/orders-by-ordered-at?nextPageToken={{nextPageToken}}
Content-Type: application/json

{
  "orderedAtFrom": "{{orderedAtFrom}}",
  "orderedAtTo": "{{orderedAtTo}}"
}

### Get all orders in from/to range

POST {{urlPrefix}}/orders-by-ordered-at?nextPageToken={{nextPageToken}}
Content-Type: application/json

{
  "orderedAtFrom": "{{orderedAtFrom}}",
  "orderedAtTo": "{{orderedAtTo}}"
}

### Get orders by customer

GET {{urlPrefix}}/orders-by-customer/{{customerId}}
