@urlPrefix = http://localhost:9000
#@urlPrefix = https://cold-poetry-2720.eu-central-1.kalix.app
@skuId = P0001

### get back ordered order sku items

GET {{urlPrefix}}/order-item-red-leaf-back-ordered/{{skuId}}
