@urlPrefix = http://localhost:9000
@entityId = geoOrder-id_51.3582985560079_-0.3704551990137_P0023_fc066a0b-128c-4c28-8afd-0779a74ecfbe

# Get order item red leaf entity

GET {{urlPrefix}}/order-item-red-leaf/{{entityId}}

