@urlPrefix = http://localhost:9000
@entityId = geoOrder-id_51.5005078033742_-0.1160359558203_P0017_e681865e-83a6-41bf-9cfb-aae211c7fdf1

# Get order item red leaf entity

GET {{urlPrefix}}/order-item-red-leaf/{{entityId}}

