@urlPrefix = http://localhost:9000
#@urlPrefix = https://cold-poetry-2720.eu-central-1.kalix.app
@skuId = P0006

### get back-ordered order item red leaves

GET {{urlPrefix}}/order-item-red-leaf-back-ordered/{{skuId}}
