@urlPrefix = http://localhost:9000
# @urlPrefix = https://flat-lab-5598.eu-central-1.kalix.app
@skuId = P0001

### get product

GET {{urlPrefix}}/product/{{skuId}}

### Load products from file

PUT {{urlPrefix}}/product-ui/create-products
Content-Type: application/json

< ./product-list.json
