@urlPrefix = http://localhost:9000
# @urlPrefix = https://cold-poetry-2720.eu-central-1.kalix.app
# @urlPrefix = https://hidden-dew-3004.us-east1.kalix.app
@skuId = P0001

### get product

GET {{urlPrefix}}/product/{{skuId}}

### Load products from file

PUT {{urlPrefix}}/product-ui/create-products
Content-Type: application/json

< ./product-list.json
