@urlPrefix = http://localhost:9000
# @urlPrefix = https://cold-poetry-2720.eu-central-1.kalix.app
@nextPageToken = NULL

### Get all products

GET {{urlPrefix}}/products/{{nextPageToken}}

### Get back ordered products

GET {{urlPrefix}}/products-back-ordered/{{nextPageToken}}

### Get products with low inventory

GET {{urlPrefix}}/products-low-inventory/{{nextPageToken}}

### Get products with some inventory

GET {{urlPrefix}}/products-some-inventory/{{nextPageToken}}
