@urlPrefix = http://localhost:9000
@orderedAtFrom = 2024-01-01T00:00:00.000Z
@orderedAtTo = 2025-01-01T00:00:00.999Z
@nextPageToken = ABCD
@customerId = customer-1

### Get all shipping orders in from/to date range

POST {{urlPrefix}}/shipping-orders-by-ordered-at?nextPageToken={{nextPageToken}}
Content-Type: application/json

{
  "orderedAtFrom": "{{orderedAtFrom}}",
  "orderedAtTo": "{{orderedAtTo}}"
}

### Get shipping orders by customerId

GET {{urlPrefix}}/shipping-orders-by-customer/{{customerId}}
