# @urlPrefix = http://localhost:9000
@urlPrefix = https://cold-poetry-2720.eu-central-1.kalix.app
@skuId = P0021

### query for available stock sku items

GET {{urlPrefix}}/stock-sku-items-available/{{skuId}}
