@urlPrefix = http://localhost:9000
@stockOrderReceivedAtFrom = 2024-01-01T00:00:00.000Z
@stockOrderReceivedAtTo = 2025-01-01T00:00:00.999Z

### Query all stock orders

POST {{urlPrefix}}/stock-orders-by-received-at
Content-Type: application/json

{
  "stockOrderReceivedAtFrom": "{{stockOrderReceivedAtFrom}}",
  "stockOrderReceivedAtTo": "{{stockOrderReceivedAtTo}}"
}
