@urlPrefix = http://localhost:9000
# @urlPrefix = https://flat-lab-5598.eu-central-1.kalix.app
@skuId = P0021

### query for available stock sku items

GET {{urlPrefix}}/stock-sku-items-available/{{skuId}}
