@urlPrefix = http://localhost:9000
#@urlPrefix = https://weathered-shadow-3441.us-east1.kalix.app
@stockOrderId = stock-order-2
@skuId = P0002
@skuName = sku name 1
@quantityTotal = 200
@orderItemsOrdered = 5
@orderItemsAvailable = 5

### UI Create a new stock order

PUT {{urlPrefix}}/stock-order-ui/{{stockOrderId}}/create
Content-Type: application/json

{
  "stockOrderId": "{{stockOrderId}}",
  "skuId": "{{skuId}}",
  "skuName": "{{skuName}}",
  "quantityTotal": {{quantityTotal}}
}

### Create a new stock order

PUT {{urlPrefix}}/stock-order/{{stockOrderId}}/create
Content-Type: application/json

{
  "stockOrderId": "{{stockOrderId}}",
  "skuId": "{{skuId}}",
  "skuName": "{{skuName}}",
  "quantityTotal": {{quantityTotal}}
}

### Create a new stock order (bad request)

PUT {{urlPrefix}}/stock-order/{{stockOrderId}}/create
Content-Type: application/json

{
  "stockOrderId": "",
  "skuId": "",
  "skuName": "",
  "quantityTotal": 0
}

### Update a stock order

PUT {{urlPrefix}}/stock-order/{{stockOrderId}}/update
Content-Type: application/json

{
  "stockOrderId": "{{stockOrderId}}",
  "orderItemsOrdered": {{orderItemsOrdered}},
  "orderItemsAvailable": {{orderItemsAvailable}}
}

### Generate stock sku items

PUT {{urlPrefix}}/stock-order/{{stockOrderId}}/generate-stock-sku-item-ids
Content-Type: application/json

{
  "stockOrderId": "{{stockOrderId}}"
}

### Get a stock order

GET {{urlPrefix}}/stock-order/{{stockOrderId}}
